version: "3.3"
   
services:

    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
        volumes:
            - "./data:/data/db"
        ports:
            - "27017:27017"
        
    web:
        build: ./project
        command: flask run --host=0.0.0.0
        volumes:
            - ./project:/usr/src/app
        ports:
            - "5001:5000"
        depends_on:
            - mongo
        env_file:
            - .env
        environment: 
            - FLASK_DEBUG=1
            - FLASK_APP=run.py
            - FLASK_ENV=development
    
    rabbit:
        image: rabbitmq:3.8-alpine
        hostname: rabbitmq1
        environment: 
            - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
            - RABBITMQ_DEFAULT_VHOST=${RABBIT_VHOST}
        ports:
            - "5672:5672"
            - "15672:15672"
